### PR TITLE
Replace referee with @sinonjs/referee

### PR DESCRIPTION
**Pull request by mroderick**
This PR replaces the `referee` dependency with `@sinonjs/referee`.

#### How to verify - mandatory

1. Observe that all tests pass on Travis
2. ?
3. Win!

### CODE REVIEW

**Comment by mantoni** [comment]
Are we going with semver here too?

**Comment by mroderick** [comment]
Do you think this deserves a new version?

**Comment by mantoni** [comment]
I mean the dependencies are specified strictly.

**Comment by mroderick** [comment]
> I mean the dependencies are specified strictly.

Oh, I just haven't gotten round to setting this repo back to normal yet. I'll do that next

**Comment by mroderick** [comment]
Please review https://github.com/sinonjs/formatio/pull/17 first, then I'll update this

**Comment by mroderick** [comment]
Fixed

**Pull request merged**
